function mainall

    %close all;

    z_gt = {"G","G","G",...
        "D","D","D",...
        "H","H","H",...
        "E","E","E","E",...
        "I","I","I",...
        "N","N","N",...
        "L","L","L",...
        "M","M","M","M",...
        "F","F",...
        "A","A","A",...
        "B","B","B",...
        "C","C","C"};

    test3_gt = {"C","C","C","C","C",...
        "N","N","N","N","N","N",...
        "D","D","D","D","D",...
        "L","L","L","L","L","L",...
        "G","G","G","G",...
        "M","M","M","M","M","M",...
        "H","H","H","H",...
        "F","F","F",...
        "F","F","F","F",...
        "H","H","H"};
    
    z_gt_counts = [5 4 5 5 5 5 6 5 7 6 6 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 4 5 5 4 5 5 5 5 5 6];
    test3_gt_counts = [5 5 5 5 5 5 5 5 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 4 5 5 5 5 5 5 5];

    mapping = containers.Map(["A","B","C","D","E","F","G","H","I","L","M","N"], [1 2 3 4 5 6 7 8 9 10 11 12]);

    total_num_leafs = sum(z_gt_counts);

    [num_images, class_full_paths, ~] = image_paths_from_dir("images/Z");

    [m,n] = calcola_ingombro_minimo_subplot(num_images);

    dummy_se = strel('disk', 0);
    se = strel('disk', 5);

    correct_guesses = 0;

    tic;

    figure_maximized;
    for i=1:num_images
        im = imresizetoarea(im2double(imread(class_full_paths{i})), 120000);

        mask = segment(im, se);
        [classificato,counts] = classify(im, mask, dummy_se);

        class_label = z_gt{i};
        expected_class = mapping(class_label);
        correct_guesses = correct_guesses + counts(expected_class);

        tsubplot(m,n,i);
        visualize_classification(classificato);
        title(class_label);
    end

    toc;

    fprintf("Accuracy: %.2f%%\n", correct_guesses / (total_num_leafs) * 100);
end